@IsTest
public class Connection extends DomainBuilder {

    public Connection(Pipeline pip, Environment source, Environment destination) {
        super(copado__Deployment_Flow_Step__c.SObjectType);
        setParent(copado__Deployment_Flow_Step__c.copado__Deployment_Flow__c, pip);
        setParent(copado__Deployment_Flow_Step__c.copado__Source_Environment__c, source);
        setParent(copado__Deployment_Flow_Step__c.copado__Destination_Environment__c, destination);
    }

    public Connection() {
        this( new Pipeline(), new Environment(), new Environment() );
    }

    public Connection(Pipeline pip) {
        this( pip, new Environment(), new Environment() );
    }

    public Connection(Environment source, Environment destination) {
        this( new Pipeline(), source, destination );
    }
}